### ISSUE TITLE
Is shade and tilt support possible?

### ISSUE THREAD

**Issue by jclusso** [safepay/cover.hd_powerview#4]
I see you wrote "This does not support Top-Down shades or tilting Venetian blinds."

I currently have shades that tilt and include a blackout shade behind them. Is this a limitation of the API or something planned for the future? Or just something someone else would need to contribute?

Thanks!

**Comment by safepay** [comment]
Good question.

Probably for someone else to implement.

It would take a fair bit of testing and don't have the shades.
