### ISSUE TITLE
Setup doesn't gracefully handle when blinds hub not reachable.

### ISSUE THREAD

**Issue by gregorymartin** [safepay/cover.hd_powerview#5]
Hi there, my hub was offline for a bit, and I noticed that when that was the case the following error shows up in the logs.  I believe that is due to the component trying to process shades even though a successful response and payload to the shades service did not happen.

Here is the detail from my log:

`2020-02-01 19:42:58 ERROR (MainThread) [homeassistant.components.cover] Error while setting up platform hd_powerview
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/hd_powerview/cover.py", line 38, in async_setup_platform
    for cover_id in cover_ids:
TypeError: 'bool' object is not iterable`

**Comment by bdraco** [comment]
We now raise PlatformNotReady so HA tries again later.

**Comment by safepay** [comment]
Closing this as this should be resolved.
