### ISSUE TITLE
Battery Level Attribute missing on One Powerview Shade

### ISSUE THREAD

**Issue by dac21** [safepay/cover.hd_powerview#6]
I have 9 of these Powerview shades.  8 of them look great in HA but one of them is missing it's battery_level attribute.  Any thoughts?

**Comment by dac21** [comment]
I removed your integration and re-added but got the same issue.  Thoughts?

**Comment by safepay** [comment]
Needs detailed debugging. I can't replicate this.

**Comment by daconrad0** [comment]
This is working after the 106 update
